---
title: "table test"
output: pdf_document
---


\begin{table}[ht]
\centering
\begin{tabular}{rrrrr}
  \hline
 & Estimate & Std. Error & t value & Pr($>$$|$t$|$) \\ 
  \hline
(Intercept) & -4671.8905 & 494.1500 & -9.45 & 0.0000 \\ 
  GA & 203.5407 & 13.5509 & 15.02 & 0.0000 \\ 
  Scort & -33.6683 & 54.3538 & -0.62 & 0.5372 \\ 
  BMI & 2.2982 & 3.2729 & 0.70 & 0.4843 \\ 
  Gender & -25.7720 & 34.8775 & -0.74 & 0.4618 \\ 
  RiskOB & -35.6236 & 38.0710 & -0.94 & 0.3519 \\ 
  Race2 & -19.0163 & 42.1063 & -0.45 & 0.6526 \\ 
  Race3 & -39.2435 & 48.9715 & -0.80 & 0.4250 \\ 
   \hline
\end{tabular}
\end{table}


\begin{table}[ht]
\centering
\begin{tabular}{rrrrr}
  \hline
 & Estimate & Std. Error & t value & Pr($>$$|$t$|$) \\ 
  \hline
(Intercept) & -331.1343 & 342.7968 & -0.97 & 0.3366 \\ 
  BMI & 5.0752 & 4.4074 & 1.15 & 0.2525 \\ 
  Gender & 53.6262 & 46.4038 & 1.16 & 0.2508 \\ 
  RiskOB & -45.6078 & 52.0619 & -0.88 & 0.3833 \\ 
  Race2 & -23.7027 & 58.1583 & -0.41 & 0.6845 \\ 
  Race3 & -147.8322 & 66.1092 & -2.24 & 0.0278 \\ 
  GAd & 144.6924 & 16.6507 & 8.69 & 0.0000 \\ 
  Scortd & 9.3753 & 67.3677 & 0.14 & 0.8896 \\ 
   \hline
\end{tabular}
\end{table}


\begin{table}[ht]
\centering
\begin{tabular}{rlrrrrrlrr}
  \hline
  & Model & df & AIC & BIC & logLik & Test & L.Ratio & p-value \\ 
  \hline
modlme  &  1 & 13.00 & 7020.89 & 7075.68 & -3497.45 &  &  &  \\ 
  modlme1  &   2 & 14.00 & 6030.58 & 6089.58 & -3001.29 & 1 vs 2 & 992.32 & 0.00 \\ 
   \hline
\end{tabular}
\end{table}









\begin{table}[!htbp] \centering 
  \caption{Result of model 4} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lcrrrrrrrr} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & EFW \\ 
\hline \\[-1.8ex] 
 Scort & $-$26.567 GA & $-$169.982$^{***}$  \\ 
  & (68.088) & (5.130)\\ 
  & \\ 
 BMI & $-$0.056 & Gender & $-$21.494$^{**}$\\ 
  & (1.035) & (10.760) \\ 
  & \\ 
 Race2 & $-$16.114 &  Race3 & $-$4.779 \\ 
  & (13.454)  & (15.568) \\ 
  & \\ 
 RiskOB & $-$9.629 & I(GA$\hat{\mkern6mu}$2) & 5.592$^{***}$ \\ 
  & (12.277) & (0.101) \\ 
  & \\ 
 Scort:GA & 1.254 & Constant & 1,441.410$^{***}$ \\ 
  & (2.308) & (75.030) \\ 
  & \\ 
\hline \\[-1.8ex] 
Observations & 500 \\ 
Log Likelihood & $-$3,001.289 & Akaike Inf. Crit. & 6,030.578 & Bayesian Inf. Crit. & 6,089.583 \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 



\begin{table}[ht] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lcrrrrrrrr} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{1}{c}{\textit{result of model 4 Dependent variable:}} \\ 
\cline{2-2} 
\\[-1.8ex] & vite \\ 
\hline \\[-1.8ex] 
 month & 0.088 &month.f & $-$0.098 \\ 
  & (0.064) & (0.078) \\ 
  & \\ 
 bcarot & 0.002$^{***}$ & month:bcarot & $-$0.0002$^{***}$ \\ 
  & (0.0002) &  (0.00002) \\ 
  & \\ 
 month.f:dose15 & $-$0.177$^{***}$&month.f:dose30 \\ 
  & (0.033) & (0.033)\\ 
  & \\ 
 month.f:dose45 & $-$0.192$^{***}$ & month.f:dose60 & $-$0.120$^{***}$ \\ 
  & (0.036) & (0.034) \\ 
  & \\ 
\hline \\[-1.8ex] 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 